package parsed

import (
	"github.com/lucianoq/hattrick/chpp"
)

// Codec ...
type Codec interface {
	Achievements(buf []byte) (*chpp.AchievementsXML, error)
	ArenaDetails(buf []byte) (*chpp.ArenaDetailsXML, error)
	Alliances(buf []byte) (*chpp.AlliancesXML, error)
	AllianceDetails(buf []byte) (*chpp.AllianceDetailsXML, error)
	Avatars(buf []byte) (*chpp.AvatarsXML, error)
	Bookmarks(buf []byte) (*chpp.BookmarksXML, error)
	Challenges(buf []byte) (*chpp.ChallengesXML, error)
	Club(buf []byte) (*chpp.ClubXML, error)
	CupMatches(buf []byte) (*chpp.CupMatchesXML, error)
	CurrentBids(buf []byte) (*chpp.CurrentBidsXML, error)
	Economy(buf []byte) (*chpp.EconomyXML, error)
	Fans(buf []byte) (*chpp.FansXML, error)
	HOFPlayers(buf []byte) (*chpp.HOFPlayersXML, error)
	LadderDetails(buf []byte) (*chpp.LadderDetailsXML, error)
	LadderList(buf []byte) (*chpp.LadderListXML, error)
	LeagueDetails(buf []byte) (*chpp.LeagueDetailsXML, error)
	LeagueFixtures(buf []byte) (*chpp.LeagueFixturesXML, error)
	Live(buf []byte) (*chpp.LiveXML, error)
	ManagerCompendium(buf []byte) (*chpp.ManagerCompendiumXML, error)
	Matches(buf []byte) (*chpp.MatchesXML, error)
	MatchesArchive(buf []byte) (*chpp.MatchesArchiveXML, error)
	MatchDetails(buf []byte) (*chpp.MatchDetailsXML, error)
	MatchLineup(buf []byte) (*chpp.MatchLineupXML, error)
	MatchOrders(buf []byte) (*chpp.MatchOrdersXML, error)
	NationalTeams(buf []byte) (*chpp.NationalTeamsXML, error)
	NationalTeamDetails(buf []byte) (*chpp.NationalTeamDetailsXML, error)
	NationalTeamMatches(buf []byte) (*chpp.NationalTeamMatchesXML, error)
	NationalPlayers(buf []byte) (*chpp.NationalPlayersXML, error)
	Players(buf []byte) (*chpp.PlayersXML, error)
	PlayerDetails(buf []byte) (*chpp.PlayerDetailsXML, error)
	PlayerEvents(buf []byte) (*chpp.PlayerEventsXML, error)
	RegionDetails(buf []byte) (*chpp.RegionDetailsXML, error)
	Search(buf []byte) (*chpp.SearchXML, error)
	StaffAvatars(buf []byte) (*chpp.StaffAvatarsXML, error)
	StaffList(buf []byte) (*chpp.StaffListXML, error)
	Supporters(buf []byte) (*chpp.SupportersXML, error)
	TeamDetails(buf []byte) (*chpp.TeamDetailsXML, error)
	TournamentDetails(buf []byte) (*chpp.TournamentDetailsXML, error)
	TournamentFixtures(buf []byte) (*chpp.TournamentFixturesXML, error)
	TournamentLeagueTables(buf []byte) (*chpp.TournamentLeagueTablesXML, error)
	TournamentList(buf []byte) (*chpp.TournamentListXML, error)
	Training(buf []byte) (*chpp.TrainingXML, error)
	TrainingEvents(buf []byte) (*chpp.TrainingEventsXML, error)
	TransferSearch(buf []byte) (*chpp.TransferSearchXML, error)
	TransferSteam(buf []byte) (*chpp.TransferSteamXML, error)
	TransfersPlayer(buf []byte) (*chpp.TransfersPlayerXML, error)
	Translations(buf []byte) (*chpp.TranslationsXML, error)
	WorldCup(buf []byte) (*chpp.WorldCupXML, error)
	WorldDetails(buf []byte) (*chpp.WorldDetailsXML, error)
	WorldLanguages(buf []byte) (*chpp.WorldLanguagesXML, error)
	YouthAvatars(buf []byte) (*chpp.YouthAvatarsXML, error)
	YouthLeagueDetails(buf []byte) (*chpp.YouthLeagueDetailsXML, error)
	YouthLeagueFixtures(buf []byte) (*chpp.YouthLeagueFixturesXML, error)
	YouthPlayerDetails(buf []byte) (*chpp.YouthPlayerDetailsXML, error)
	YouthPlayerList(buf []byte) (*chpp.YouthPlayerListXML, error)
	YouthTeamDetails(buf []byte) (*chpp.YouthTeamDetailsXML, error)
}
